# Álgebra Lineal
Calculo de Valores y Vecotres Propios en Python

In [ ]:
import numpy as l

# Sección 8.1

In [ ]:
##6)
##Ingresamos la matriz A
A=l.array([[1, 0], [0, 1]])
##Calculamos Valores y Vectores Propios con la funcion lineal.eig
valores,vectores=l.linalg.eig(A)
##Imprimmos los valores
valores

array([1., 1.])

In [ ]:
##6)
##Ingresamos la matriz A
A=l.array([[-1, 0], [0, -1]])
##Calculamos Valores y Vectores Propios con la funcion lineal.eig
valores,vectores=l.linalg.eig(A)
##Imprimmos los valores
valores

array([-1., -1.])

# Sección 8.2

## Programación de Valores Propios

In [ ]:
##3.a)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([[1, 2], [3, 2]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)


Valores Propios:
[-1.  4.]


In [ ]:
##3.b)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([[3, 2], [-1, 0]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[2. 1.]


In [ ]:
##3.c)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([[-2, -7], [1, 2]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)
##j=i representa la parte imaginaria
##e^{-16} se aproxima a 0
##1.73 se aproxima a \sqrt{3}

Valores Propios:
[1.66533454e-16+1.73205081j 1.66533454e-16-1.73205081j]


**Notas**
$$j= i$$
$$0 \approx e^{-16}$$
$$1.733 \approx \sqrt{3}$$

In [ ]:
##3.d)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([[1, 4], [2, 3]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[-1.  5.]


In [ ]:
##4.a)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([[4, 0,1], [-2, 1,0], [-2, 0,1]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[1. 3. 2.]


In [ ]:
##4.b)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([[1, -3,3], [3, -5,3], [6, -6,4]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[ 4.+0.00000000e+00j -2.+1.10465796e-15j -2.-1.10465796e-15j]


In [ ]:
##4.c)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([[3, 1,1], [2, 4,2], [1,1 ,3]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[2. 6. 2.]


In [ ]:
##4.d)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([[1, 2,2], [1, 2,-1], [-1, 1,4]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[1.+0.00000000e+00j 3.+5.15692414e-16j 3.-5.15692414e-16j]


In [ ]:
##5.a)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([[2, -1], [1, 0]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[1. 1.]


In [ ]:
##5.b)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([[1,1], [0, 1]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[1. 1.]


In [ ]:
##5.c)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([[2, 0], [1, 2]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[2. 2.]


In [ ]:
##5.d)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([[2, -3], [1, -1]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[0.5+0.8660254j 0.5-0.8660254j]


In [ ]:
##6.a)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([[1, 1,1], [0,1, 1],[0,0, 1]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[1. 1. 1.]


In [ ]:
##6.b)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([[1, 1,0], [0,1, 1],[0,0, 1]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[1. 1. 1.]


## Ejercicio 7

In [ ]:
##7.a)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([[0,1, 0,0], [0,0, 1,0],[0,0,0, 1],[1,0,0,0]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[-1.00000000e+00+0.j  8.32667268e-17+1.j  8.32667268e-17-1.j
  1.00000000e+00+0.j]


Nota
$$
8.3266e^{-17}+1j=i
$$
$$
8.3266e^{-17}-1j=-i
$$

In [ ]:
##7.b)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([ [-1, 0,1],[-1,3, 0],[-4,13,-1]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[ 2. +0.j        -0.5+0.8660254j -0.5-0.8660254j]


Nota
$$
0.8660j=\frac{\sqrt{3}}{2}i
$$
$$
-0.8660j=-\frac{\sqrt{3}}{2}i
$$

## Ejercicio 8

In [ ]:
##8.a)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([ [2,4],[5,3]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[-2.  7.]


In [ ]:
##8.b)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([ [1,2],[2,-2]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[ 2. -3.]


In [ ]:
##8.c)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([ [3,2],[-2,3]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[3.+2.j 3.-2.j]


In [ ]:
##8.d)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([ [-1,2,2],[2,2,2],[-3,-6,-6]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[-2.22044605e-15 -2.00000000e+00 -3.00000000e+00]


Nota
$$
-2.22e^{-15}\approx 0
$$

In [ ]:
##8.e)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([ [3,2,1],[0,1,2],[0,1,-1]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[ 3.          1.73205081 -1.73205081]


Nota
$$
\sqrt{3} \approx 1.7320
$$
$$
-\sqrt{3} \approx -1.7320
$$

In [ ]:
##8.f)
##Importacion Nuestra libreria Numpy
import numpy as l
##Definimos una funcion para el calculo de valores y vectores propios
def valores_propios(A):
    ##Ocupas la funcionde Python que calcula los vectores y valores propios (linalg.eig())
    valores_propios,vectores_propios = l.linalg.eig(A)
    ##La funcion regresa los valores y vectores propios
    return valores_propios
##A es nuestra matriz
A=l.array([ [-1,4,-2],[-3,4,0],[-3,1,3]])
##Los valores y vectores los igualamos a lo calcula nuestra funcion
valores=valores_propios(A)
print("Valores Propios:")
print(valores)

Valores Propios:
[1. 2. 3.]


## Programación de Vectores Propios

In [ ]:
##Ejercicio 3.5 a)
##Ingresamos la matriz A
A=l.array([[1, 2], [3, 2]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[1], [3/2]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[1], [ -1]])
##Ingresamos los valores propios
t1=4
t2=-1
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")

Tu resultado es correcto para v1
Tu resultado es correcto para v2


In [ ]:
##Ejercicio 3.5 a)
##Ingresamos la matriz A
A=l.array([[3, 2], [-1, 0]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[1], [-1/2]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[1], [ -1]])
##Ingresamos los valores propios
t1=2
t2=1
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")

Tu resultado es correcto para v1
Tu resultado es correcto para v2


In [ ]:
##Ejercicio 3.5 b)
##Ingresamos la matriz A
A=l.array([[3, 2], [-1, 0]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[1], [-1/2]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[1], [ -1]])
##Ingresamos los valores propios
t1=2
t2=1
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")

Tu resultado es correcto para v1
Tu resultado es correcto para v2


**Notas**
$$j= i$$
$$0 \approx e^{-16}$$
$$1.733 \approx \sqrt{3}$$

In [ ]:
##Ejercicio 3.5 c)
##Ingresamos la matriz A
A=l.array([[-2, -7], [1, 2]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[1], [1/(1.733j-2)]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[1], [1/(-1.733j+2)]])
##Ingresamos los valores propios
t1=1.733j
t2=1.733j
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")

Tu resultado es incorrecto para v1
Tu resultado es incorrecto para v2


In [ ]:
##Ejercicio 3.5 d)
##Ingresamos la matriz A
A=l.array([[2, -3], [1, -1]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[(3/2+1.733/2j)], [1]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[(3/2-1.733/2j)], [1]])
##Ingresamos los valores propios
t1=(1/2+1.733/2j)
t2=-(1/2-1.733/2j)
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")

Tu resultado es incorrecto para v1
Tu resultado es incorrecto para v2


## Ejercicio 4

In [ ]:
##Ejercicio 4.a)
##Ingresamos la matriz A
A=l.array([[4, 0,1], [-2,1, 0],[-2,0, 1]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[0], [1],[0]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[1], [-2],[-2]])
##Ingresamos el vector propio obtenido para \lambda3
v3=l.array([[1], [-1],[-1]])
##Ingresamos los valores propios
t1=1
t2=2
t3=3
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Multiplicacion la matriz por su vector propio 3
Av3=l.dot(A,v3)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Mulplicamos el vector por su valor propio
t3v3=v3*t3
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")
if l.all(Av3==t3v3):
  print("Tu resultado es correcto para v3")
else:
  print("Tu resultado es incorrecto para v3")

Tu resultado es correcto para v1
Tu resultado es correcto para v2
Tu resultado es correcto para v3


In [ ]:
##Ejercicio 4.b)
##Ingresamos la matriz A
A=l.array([[1, -3,3], [3,-5, 3],[6,-6, 4]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[1], [1],[2]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[1], [1],[0]])
##Ingresamos el vector propio obtenido para \lambda3
v3=l.array([[1], [1],[0]])
##Ingresamos los valores propios
t1=4
t2=-2
t3=-2
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Multiplicacion la matriz por su vector propio 3
Av3=l.dot(A,v3)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Mulplicamos el vector por su valor propio
t3v3=v3*t3
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")
if l.all(Av3==t3v3):
  print("Tu resultado es correcto para v3")
else:
  print("Tu resultado es incorrecto para v3")

Tu resultado es correcto para v1
Tu resultado es correcto para v2
Tu resultado es correcto para v3


In [ ]:
##Ejercicio 4.c)
##Ingresamos la matriz A
A=l.array([[3, 1,1], [2,4, 2],[1,1, 3]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[-2], [1],[1]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[1], [2],[1]])
##Ingresamos el vector propio obtenido para \lambda3
v3=l.array([[-2], [1],[1]])
##Ingresamos los valores propios
t1=2
t2=6
t3=2
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Multiplicacion la matriz por su vector propio 3
Av3=l.dot(A,v3)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Mulplicamos el vector por su valor propio
t3v3=v3*t3
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")
if l.all(Av3==t3v3):
  print("Tu resultado es correcto para v3")
else:
  print("Tu resultado es incorrecto para v3")

Tu resultado es correcto para v1
Tu resultado es correcto para v2
Tu resultado es correcto para v3


In [ ]:
##Ejercicio 4.d)
##Ingresamos la matriz A
A=l.array([[1, 2,2], [1,2, -1],[-1,1, 4]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[1], [0],[1]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[1], [0],[1]])
##Ingresamos el vector propio obtenido para \lambda3
v3=l.array([[2], [-1],[1]])
##Ingresamos los valores propios
t1=3
t2=3
t3=1
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Multiplicacion la matriz por su vector propio 3
Av3=l.dot(A,v3)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Mulplicamos el vector por su valor propio
t3v3=v3*t3
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")
if l.all(Av3==t3v3):
  print("Tu resultado es correcto para v3")
else:
  print("Tu resultado es incorrecto para v3")

Tu resultado es correcto para v1
Tu resultado es correcto para v2
Tu resultado es correcto para v3


## Ejercicio 5

In [ ]:
##Ejercicio 5 a)
##Ingresamos la matriz A
A=l.array([[2, -1], [1, 0]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[1], [1]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[1], [ 1]])
##Ingresamos los valores propios
t1=1
t2=1
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")

Tu resultado es correcto para v1
Tu resultado es correcto para v2


In [ ]:
##Ejercicio 5 b)
##Ingresamos la matriz A
A=l.array([[1, 1], [0, 1]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[1], [0]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[1], [0]])
##Ingresamos los valores propios
t1=1
t2=1
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")

Tu resultado es correcto para v1
Tu resultado es correcto para v2


In [ ]:
##Ejercicio 5 c)
##Ingresamos la matriz A
A=l.array([[2, 0], [1, 2]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[0], [1]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[0], [1]])
##Ingresamos los valores propios
t1=2
t2=2
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")

Tu resultado es correcto para v1
Tu resultado es correcto para v2


In [ ]:
##Ejercicio 6.a)
##Ingresamos la matriz A
A=l.array([[1, 1,1], [0,1, 1],[0,0, 1]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[1], [0],[0]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[1], [0],[0]])
##Ingresamos el vector propio obtenido para \lambda3
v3=l.array([[1], [0],[0]])
##Ingresamos los valores propios
t1=1
t2=1
t3=1
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Multiplicacion la matriz por su vector propio 3
Av3=l.dot(A,v3)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Mulplicamos el vector por su valor propio
t3v3=v3*t3
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")
if l.all(Av3==t3v3):
  print("Tu resultado es correcto para v3")
else:
  print("Tu resultado es incorrecto para v3")

Tu resultado es correcto para v1
Tu resultado es correcto para v2
Tu resultado es correcto para v3


In [ ]:
##Ejercicio 6.b)
##Ingresamos la matriz A
A=l.array([[1, 1,0], [0,1, 1],[0,0, 1]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[1], [0],[0]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[1], [0],[0]])
##Ingresamos el vector propio obtenido para \lambda3
v3=l.array([[1], [0],[0]])
##Ingresamos los valores propios
t1=1
t2=1
t3=1
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Multiplicacion la matriz por su vector propio 3
Av3=l.dot(A,v3)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Mulplicamos el vector por su valor propio
t3v3=v3*t3
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")
if l.all(Av3==t3v3):
  print("Tu resultado es correcto para v3")
else:
  print("Tu resultado es incorrecto para v3")

Tu resultado es correcto para v1
Tu resultado es correcto para v2
Tu resultado es correcto para v3




## Ejercicio 7

In [ ]:
##Ejercicio 7 a)
##Ingresamos la matriz A
A=l.array([[0, 1,0,0], [0,0,1,0],[0,0,0,1],[1,0,0,0]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[1], [1],[1],[1]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[1], [-1],[1],[-1]])
##Ingresamos el vector propio obtenido para \lambda3
v3=l.array([[1], [1j],[-1],[-1j]])
##Ingresamos el vector propio obtenido para \lambda4
v4=l.array([[1], [-1j],[-1],[1j]])
##Ingresamos los valores propios
t1=1
t2=-1
t3=1j
t4=-1j
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Multiplicacion la matriz por su vector propio 2
Av3=l.dot(A,v3)
##Multiplicacion la matriz por su vector propio 2
Av4=l.dot(A,v4)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Mulplicamos el vector por su valor propio
t3v3=v3*t3
##Mulplicamos el vector por su valor propio
t4v4=v4*t4
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")
if l.all(Av3==t3v3):
  print("Tu resultado es correcto para v3")
else:
  print("Tu resultado es incorrecto para v3")
if l.all(Av4==t4v4):
  print("Tu resultado es correcto para v4")
else:
  print("Tu resultado es incorrecto para v4")

Tu resultado es correcto para v1
Tu resultado es correcto para v2
Tu resultado es correcto para v3
Tu resultado es correcto para v4


In [ ]:
##Ejercicio 7.b)
##Ingresamos la matriz A
A=l.array([[-1, 0,1], [-1,3, 0],[-4,13, -1]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[1], [1],[3]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[3.5-1.7320j], [1],[4.75+5.1961j]])
##Ingresamos el vector propio obtenido para \lambda3
v3=l.array([[3.5+1.7350j], [1],[4.75-5.1961j]])
##Ingresamos los valores propios
t1=2
t2=-0.5+0.8660254j
t3=-0.5-0.8660254j
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Multiplicacion la matriz por su vector propio 3
Av3=l.dot(A,v3)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Mulplicamos el vector por su valor propio
t3v3=v3*t3
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")
if l.all(Av3==t3v3):
  print("Tu resultado es correcto para v3")
else:
  print("Tu resultado es incorrecto para v3")

Tu resultado es correcto para v1
Tu resultado es incorrecto para v2
Tu resultado es incorrecto para v3


## Ejercicio 8

In [ ]:
##Ejercicio 8 a)
##Ingresamos la matriz A
A=l.array([[2, 4], [5, 3]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[4/5], [1]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[-1], [1]])
##Ingresamos los valores propios
t1=7
t2=-2
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")

Tu resultado es incorrecto para v1
Tu resultado es correcto para v2


In [ ]:
##Ejercicio 8 b)
##Ingresamos la matriz A
A=l.array([[1, 2], [2, -2]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[1], [-2]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[1], [1/2]])
##Ingresamos los valores propios
t1=-3
t2=2
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")

Tu resultado es correcto para v1
Tu resultado es correcto para v2


In [ ]:
##Ejercicio 8 c)
##Ingresamos la matriz A
A=l.array([[3, 2], [-2, 3]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[1], [1j]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[1], [-1j]])
##Ingresamos los valores propios
t1=3+2j
t2=3-2j
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")

Tu resultado es correcto para v1
Tu resultado es correcto para v2


In [ ]:
##Ejercicio 8 d)
##Ingresamos la matriz A
A=l.array([[-1, 2,2], [2, 2,2],[-3,-6,-6]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[1], [0],[-1]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[0], [1],[-1]])
##Ingresamos el vector propio obtenido para \lambda3
v3=l.array([[1], [-1/2],[0]])
##Ingresamos los valores propios
t1=-3
t2=0
t3=-2
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Multiplicacion la matriz por su vector propio 3
Av3=l.dot(A,v3)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Mulplicamos el vector por su valor propio
t3v3=v3*t3
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")
if l.all(Av3==t3v3):
  print("Tu resultado es correcto para v3")
else:
  print("Tu resultado es incorrecto para v3")

Tu resultado es correcto para v1
Tu resultado es correcto para v2
Tu resultado es correcto para v3


In [ ]:
##Ejercicio 8 e)
##Ingresamos la matriz A
A=l.array([[3, 2,1], [0, 1,2],[0,1,-1]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[1], [0],[0]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[-5.0980], [2.7320],[1]])
##Ingresamos el vector propio obtenido para \lambda3
v3=l.array([[0.0980], [-0.7320],[1]])
##Ingresamos los valores propios
t1=3
t2=1.7320
t3=-1.7320
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Multiplicacion la matriz por su vector propio 3
Av3=l.dot(A,v3)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Mulplicamos el vector por su valor propio
t3v3=v3*t3
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")
if l.all(Av3==t3v3):
  print("Tu resultado es correcto para v3")
else:
  print("Tu resultado es incorrecto para v3")

Tu resultado es correcto para v1
Tu resultado es incorrecto para v2
Tu resultado es incorrecto para v3


In [ ]:
##Ejercicio 8 f)
##Ingresamos la matriz A
A=l.array([[-1, 4,-2], [-3, 4,0],[-3,1,3]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[2], [3],[3]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[1], [1],[1]])
##Ingresamos el vector propio obtenido para \lambda3
v3=l.array([[1], [3],[4]])
##Ingresamos los valores propios
t1=2
t2=1
t3=3
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Multiplicacion la matriz por su vector propio 3
Av3=l.dot(A,v3)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Mulplicamos el vector por su valor propio
t3v3=v3*t3
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")
if l.all(Av3==t3v3):
  print("Tu resultado es correcto para v3")
else:
  print("Tu resultado es incorrecto para v3")

Tu resultado es correcto para v1
Tu resultado es correcto para v2
Tu resultado es correcto para v3


## Sección 8.3

In [ ]:
##Ingresamos la matriz A
A=l.array([[2, -1], [-1, 2]])
##Calculamos Valores y Vectores Propios con la funcion lineal.eig
valores,vectores=l.linalg.eig(A)
##Imprimmos los valores
valores

array([3., 1.])

In [ ]:
##Ingresamos la matriz A
A=l.array([[1, 1], [1, 0]])
##Calculamos Valores y Vectores Propios con la funcion lineal.eig
valores,vectores=l.linalg.eig(A)
##Imprimmos los valores
valores

array([ 1.61803399, -0.61803399])

In [ ]:
##Ingresamos la matriz A
A=l.array([[1,-1,0], [-1, 2,-1], [0, -1,1]])
##Calculamos Valores y Vectores Propios con la funcion lineal.eig
valores,vectores=l.linalg.eig(A)
##Imprimmos los valores
valores

array([ 3.00000000e+00,  1.00000000e+00, -3.36770206e-17])

In [ ]:
##Ingresamos la matriz A
A=l.array([[2,-1,0], [-1, 2,-1], [0, -1,2]])
##Calculamos Valores y Vectores Propios con la funcion lineal.eig
valores,vectores=l.linalg.eig(A)
##Imprimmos los valores
valores

array([3.41421356, 2.        , 0.58578644])

In [ ]:
##Ingresamos la matriz A
A=l.array([[3,5/2], [5/2,-4]])
##Calculamos Valores y Vectores Propios con la funcion lineal.eig
valores,vectores=l.linalg.eig(A)
##Imprimmos los valores
valores

array([ 3.80116263, -4.80116263])

## Ejercicios Examen Pasado

In [ ]:
##Ingresamos la matriz A
A=l.array([[3,2], [-1,0]])
##Calculamos Valores y Vectores Propios con la funcion lineal.eig
valores,vectores=l.linalg.eig(A)
##Imprimmos los valores
valores

array([2., 1.])

In [ ]:
##Ingresamos la matriz A
A=l.array([[1,4], [2,3]])
##Calculamos Valores y Vectores Propios con la funcion lineal.eig
valores,vectores=l.linalg.eig(A)
##Imprimmos los valores
valores

array([-1.,  5.])

In [ ]:
##Ingresamos la matriz A
A=l.array([[3, 2], [-1, 0]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[1], [-1/2]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[1], [-1]])
##Ingresamos los valores propios
t1=2
t2=1
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")

Tu resultado es correcto para v1
Tu resultado es correcto para v2


In [ ]:
##Ingresamos la matriz A
A=l.array([[1, 4], [2, 3]])
##Ingresamos el vector propio obtenido para \lambda1
v1=l.array([[1], [1]])
##Ingresamos el vector propio obtenido para \lambda2
v2=l.array([[1], [-1/2]])
##Ingresamos los valores propios
t1=5
t2=-1
##Multiplicacion la matriz por su vector propio 1
Av1=l.dot(A,v1)
##Multiplicacion la matriz por su vector propio 2
Av2=l.dot(A,v2)
##Mulplicamos el vector por su valor propio
t1v1=v1*t1
##Mulplicamos el vector por su valor propio
t2v2=v2*t2
##Escribimos la condicio para que nos diga si el resultados es correto
if l.all(Av1==t1v1):
  print("Tu resultado es correcto para v1")
else:
  print("Tu resultado es incorrecto para v1")
if l.all(Av2==t2v2):
  print("Tu resultado es correcto para v2")
else:
  print("Tu resultado es incorrecto para v2")

Tu resultado es correcto para v1
Tu resultado es correcto para v2
